# ArkSpace Neural Payload Specification
# Version: 1.0.0
# Last Updated: January 2026

apiVersion: arkspace.me/v1
kind: Payload
metadata:
  name: neuromorphic-neural-payload
  description: Neuromorphic processor payload for SNN consciousness substrate
  version: "1.0.0"

spec:
  # =============================================================================
  # OVERVIEW
  # =============================================================================
  overview:
    purpose: |
      Primary computational payload for running Spiking Neural Networks (SNNs)
      that serve as the synthetic substrate for consciousness transfer. Designed
      for real-time, low-power neural computation in the space environment.
    
    key_requirements:
      - real_time_snn_processing
      - low_power_operation
      - radiation_tolerance
      - high_bandwidth_io
      - secure_key_storage

  # =============================================================================
  # NEUROMORPHIC PROCESSOR
  # =============================================================================
  processor:
    type: neuromorphic_asic
    architecture: event_driven_asynchronous
    
    # Neural capacity
    capacity:
      neurons:
        total: 100_000_000        # 100M neurons
        per_core: 128             # Distributed across cores
        core_count: 781_250       # ~780K cores
        
      synapses:
        total: 100_000_000_000    # 100B synapses
        per_neuron_avg: 1000
        per_neuron_max: 10000
        
      spike_rate:
        per_neuron_max_hz: 1000
        aggregate_max_per_s: 10_000_000_000  # 10B spikes/s
    
    # Neuron model
    neuron_model:
      type: leaky_integrate_and_fire
      
      parameters:
        membrane_time_constant_ms:
          range: [1, 100]
          precision_bits: 16
          
        threshold_mv:
          range: [-100, 100]
          precision_bits: 16
          
        reset_potential_mv:
          range: [-100, 0]
          precision_bits: 16
          
        refractory_period_ms:
          range: [0, 10]
          precision_bits: 8
          
      state_variables:
        - membrane_potential: float32
        - last_spike_time: uint64
        - refractory_counter: uint16
        
      extensions:
        - adaptation_current
        - dendritic_delay
        - stochastic_threshold
    
    # Synapse model
    synapse_model:
      weight:
        precision_bits: 16
        signed: true
        range: [-32768, 32767]
        
      delay:
        precision_bits: 8
        range_ms: [1, 16]
        
      plasticity:
        types:
          - stdp
          - reward_modulated_stdp
          - homeostatic
          
        stdp_parameters:
          a_plus: float16
          a_minus: float16
          tau_plus_ms: float16
          tau_minus_ms: float16
          
      state_variables:
        - weight: float16
        - eligibility_trace: float16
        
    # Learning
    learning:
      online_learning: true
      batch_learning: true
      
      algorithms:
        - spike_timing_dependent_plasticity
        - surrogate_gradient_descent
        - evolutionary_optimization
        
      update_granularity:
        per_spike: true
        per_epoch: true
        
    # Timing
    timing:
      time_resolution_us: 1
      global_sync: false  # Asynchronous
      simulation_to_real_time_ratio: 1.0
      max_spike_processing_latency_us: 100

  # =============================================================================
  # MEMORY SYSTEM
  # =============================================================================
  memory:
    on_chip:
      type: sram
      total_mb: 256
      
      allocation:
        neuron_state_mb: 100
        synapse_weights_mb: 128
        spike_queues_mb: 16
        learning_buffers_mb: 8
        system_mb: 4
        
      bandwidth_gbps: 1000
      latency_ns: 10
      
    external:
      type: lpddr4x
      total_gb: 16
      
      allocation:
        full_state_snapshot_gb: 8
        model_storage_gb: 4
        telemetry_buffer_gb: 2
        spare_gb: 2
        
      bandwidth_gbps: 50
      latency_ns: 100
      
    state_checkpointing:
      interval_s: 1
      full_checkpoint_size_gb: 2
      incremental_checkpoint_size_mb: 100
      checkpoint_time_ms: 50

  # =============================================================================
  # INTERFACES
  # =============================================================================
  interfaces:
    # High-speed OISL interface
    oisl:
      type: pcie_gen4
      lanes: 8
      bandwidth_gbps: 126  # ~16 GB/s bidirectional
      
      dma:
        channels: 4
        max_transfer_mb: 64
        scatter_gather: true
        
      protocol_offload:
        encryption: aes_256_gcm_hardware
        compression: lz4_hardware
        crc: hardware
        
    # Control interface (to satellite bus)
    control:
      type: spi
      clock_mhz: 50
      
      functions:
        - power_management
        - configuration
        - status_monitoring
        - firmware_update
        
    # Debug interface
    debug:
      type: jtag
      
      capabilities:
        - breakpoints
        - memory_access
        - trace_capture
        - performance_counters
        
    # Telemetry interface
    telemetry:
      type: uart
      baud: 3000000
      
      data:
        - spike_statistics
        - power_consumption
        - temperature
        - error_counts

  # =============================================================================
  # POWER MANAGEMENT
  # =============================================================================
  power:
    operating_modes:
      - name: full_active
        description: All neurons active, maximum spike rate
        power_w: 100
        neurons_active_percent: 100
        
      - name: active
        description: Typical operation
        power_w: 50
        neurons_active_percent: 50
        
      - name: low_power
        description: Reduced activity for power saving
        power_w: 20
        neurons_active_percent: 20
        
      - name: standby
        description: Minimal activity, maintaining state
        power_w: 5
        neurons_active_percent: 1
        
      - name: sleep
        description: State preserved in external memory
        power_w: 1
        neurons_active_percent: 0
        
    voltage_domains:
      core: 0.8V
      io: 1.8V
      memory: 1.1V
      
    dynamic_scaling:
      enabled: true
      voltage_scaling: true
      frequency_scaling: true
      neuron_gating: true  # Disable inactive neurons
      
    power_monitoring:
      granularity: per_core_cluster
      sample_rate_hz: 100
      
    thermal_throttling:
      threshold_c: 75
      action: reduce_spike_rate

  # =============================================================================
  # THERMAL DESIGN
  # =============================================================================
  thermal:
    heat_dissipation:
      max_tdp_w: 100
      typical_w: 50
      
    package:
      type: flip_chip_bga
      size_mm: [50, 50]
      thermal_interface: thermal_paste
      
    cooling:
      method: conductive_to_radiator
      heat_spreader: copper
      thermal_resistance_c_w: 0.5
      
    temperature_limits:
      junction_max_c: 85
      junction_target_c: 65
      case_max_c: 70
      
    sensors:
      count: 8
      distribution: across_die
      accuracy_c: 1

  # =============================================================================
  # RELIABILITY
  # =============================================================================
  reliability:
    radiation:
      total_ionizing_dose_krad: 50
      single_event_upset:
        rate_per_bit_day: 1e-10
        mitigation: ecc_and_tmr
      single_event_latchup:
        threshold_mev_cm2_mg: 75
        protected: true
        
    error_correction:
      memory:
        type: secded_ecc
        correction_bits: 1
        detection_bits: 2
      logic:
        critical_registers: tmr
        
    fault_tolerance:
      neuron_failure:
        detection: spike_monitoring
        mitigation: redundant_mapping
        max_failed_percent: 10
        
      synapse_failure:
        detection: weight_bounds_check
        mitigation: weight_redistribution
        max_failed_percent: 5
        
    watchdog:
      hardware_watchdog: true
      timeout_ms: 1000
      action: reset_and_restore
      
    health_monitoring:
      self_test:
        on_boot: full
        periodic: daily
      diagnostics:
        memory_scrubbing: continuous
        logic_checking: on_demand

  # =============================================================================
  # SECURITY
  # =============================================================================
  security:
    secure_enclave:
      type: arm_trustzone
      isolation: hardware
      
      protected_functions:
        - key_storage
        - encryption_operations
        - authentication
        - secure_boot
        
      key_storage:
        slots: 16
        key_types:
          - aes_256
          - x25519
          - ed25519
        tamper_response: key_zeroization
        
    secure_boot:
      enabled: true
      root_of_trust: hardware_fused
      chain_validation: all_stages
      rollback_protection: yes
      
    runtime_security:
      memory_protection: mpu
      execution_protection: nx_bit
      secure_debug: authenticated
      
    encryption:
      engines:
        - type: aes_gcm
          performance_gbps: 10
        - type: sha256
          performance_gbps: 5
          
    attestation:
      remote_attestation: supported
      quote_generation: secure_enclave
      
  # =============================================================================
  # SOFTWARE INTERFACE
  # =============================================================================
  software:
    runtime:
      type: custom_snn_runtime
      
      api:
        neuron_operations:
          - create_neuron
          - delete_neuron
          - set_parameters
          - get_state
          
        synapse_operations:
          - create_synapse
          - delete_synapse
          - set_weight
          - get_weight
          
        network_operations:
          - load_model
          - save_model
          - start_simulation
          - stop_simulation
          - inject_spikes
          - read_spikes
          
        state_operations:
          - checkpoint_create
          - checkpoint_restore
          - state_export
          - state_import
          
    model_format:
      supported:
        - nengo_compiled
        - custom_binary
        - pytorch_snn_export
        
      max_model_size_gb: 4
      hot_swap: supported
      
    firmware:
      update_mechanism: secure_ota
      a_b_partitioning: yes
      rollback: supported
      
    diagnostics:
      performance_counters: 64
      trace_buffer_mb: 16
      spike_logging: optional

  # =============================================================================
  # PHYSICAL SPECIFICATIONS
  # =============================================================================
  physical:
    dimensions_mm:
      length: 100
      width: 100
      height: 20
      
    mass_g: 500
    
    mounting:
      type: standard_pc104
      thermal_interface: required
      
    connectors:
      oisl:
        type: samtec_firefly
        position: edge
      control:
        type: micro_d_15
        position: edge
      debug:
        type: 10pin_jtag
        position: top
        
    environmental:
      operating_temp_c: [-20, 70]
      storage_temp_c: [-40, 85]
      vibration_g: 20
      shock_g: 100

# =============================================================================
# TELEMETRY DEFINITION
# =============================================================================
telemetry:
  housekeeping:
    sample_rate_hz: 1
    
    metrics:
      - name: processor_temperature_c
        type: float
      - name: power_consumption_w
        type: float
      - name: neurons_active_count
        type: uint32
      - name: spikes_per_second
        type: uint64
      - name: memory_utilization_percent
        type: float
      - name: error_count
        type: uint32
        
  performance:
    sample_rate_hz: 10
    
    metrics:
      - name: spike_processing_latency_us
        type: histogram
      - name: oisl_throughput_gbps
        type: float
      - name: checkpoint_duration_ms
        type: float
      - name: learning_updates_per_second
        type: uint64

  alerts:
    - name: over_temperature
      condition: processor_temperature_c > 80
      severity: critical
      action: thermal_throttle
      
    - name: high_error_rate
      condition: error_count_delta_per_minute > 100
      severity: warning
      action: log_and_notify
      
    - name: memory_exhausted
      condition: memory_utilization_percent > 95
      severity: critical
      action: reduce_activity
